:steps:
  - :name: 01-etl-tstamps
    :queries:
      - :name: 01-etl-tstamps
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/01-etl-tstamps/01-etl-tstamps.sql
  - :name: 03-events-enriched
    :queries:
      - :name: 03-01-join-unstructured
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/03-events-enriched/03-01-join-unstructured.sql
  - :name: 03-events-enriched
    :queries:
      - :name: 03-02-join-users
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/03-events-enriched/03-02-join-users.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-01-basic
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-01-basic.sql
      - :name: 04-02-geo
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-02-geo.sql
      - :name: 04-03-landing-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-03-landing-page.sql
      - :name: 04-04-exit-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-04-exit-page.sql
      - :name: 04-05-source
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-05-source.sql
      - :name: 04-06-tech
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-06-tech.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-07-consolidate
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-07-consolidate.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-08-to-load-part-1
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-08-to-load-part-1.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-09-to-load-part-2
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-09-to-load-part-2.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-10-to-load-part-3
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-10-to-load-part-3.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-11-to-load-complete
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-11-to-load-complete.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-12-move-to-pivot
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-12-move-to-pivot.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-13-move-to-in-progress
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/04-sessions/04-13-move-to-in-progress.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-01-basic
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-01-basic.sql
      - :name: 05-02-landing-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-02-landing-page.sql
      - :name: 05-03-source
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-03-source.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-04-consolidate
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-04-consolidate.sql
      - :name: 05-05-move-to-old
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-05-move-to-old.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-06-move-to-pivot-part-1
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-06-move-to-pivot-part-1.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-07-move-to-pivot-part-2
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-07-move-to-pivot-part-2.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-08-move-to-pivot-part-3
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/05-visitors/05-08-move-to-pivot-part-3.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-01-new
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-01-new.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-02-to-load-part-1
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-02-to-load-part-1.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-03-to-load-part-2
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-03-to-load-part-2.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-04-to-load-part-3
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-04-to-load-part-3.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-05-to-load-complete
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-05-to-load-complete.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-06-move-to-pivot
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-06-move-to-pivot.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-07-move-to-in-progress
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/06-page-views/06-07-move-to-in-progress.sql
  - :name: 07-structured-events
    :queries:
      - :name: 07-01-structured-events
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/07-structured-events/07-01-structured-events.sql
  - :name: 08-move-to-atomic
    :queries:
      - :name: 08-01-events
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/08-move-to-atomic/08-01-events.sql
  - :name: 09-vacuum
    :queries:
      - :name: 09-vacuum
        :file: snowplow/5-analytics/redshift-analytics/data-models/incremental/03-incremental-runs/sql/09-vacuum/09-vacuum.sql